Repository Kuama-IT/k-music-swift, pull requests merged in 2022-09, with the labels that each got.

#39 feat(SAPlayer) bump version
  Example/Podfile.lock
  Example/kMusicSwift.xcodeproj/project.pbxproj
  Example/kMusicSwift/ViewController.swift
  kMusicSwift.podspec
  kMusicSwift/Classes/AudioSourcePlayingStatus.swift
  kMusicSwift/Classes/JustAudioPlayer.swift
Labels: size/L

#38 Audio effects
  Example/kMusicSwift/ViewController.swift
  kMusicSwift/Classes/AudioEffects/AudioEffect.swift
  kMusicSwift/Classes/AudioEffects/DelayAudioEffect.swift
  kMusicSwift/Classes/AudioEffects/DistortionAudioEffect.swift
  kMusicSwift/Classes/AudioEffects/ReverbAudioEffect.swift
  kMusicSwift/Classes/AudioSource/AudioSource.swift
  kMusicSwift/Classes/AudioSource/ClippingAudioSource.swift
  kMusicSwift/Classes/AudioSource/LocalAudioSource.swift
  kMusicSwift/Classes/AudioSource/LoopingAudioSource.swift
  kMusicSwift/Classes/AudioSource/RemoteAudioSource.swift
  kMusicSwift/Classes/JustAudioPlayer.swift
Labels: size/L

#40 update todo
  TODO.md
Labels: size/S

#43 fix: publish states
  kMusicSwift/Classes/AudioSource/LocalAudioSource.swift
  kMusicSwift/Classes/JustAudioPlayer.swift
Labels: size/M

#44 feat: allow users to stop writing engine output to file
  kMusicSwift/Classes/JustAudioPlayer.swift
Labels: size/M

#45 feat: allow to set global effects
  kMusicSwift/Classes/JustAudioPlayer.swift
Labels: size/S
